PrefillWorker:
  model: /data/models/QwQ-32B
  served_model_name: Qwen/QwQ-32B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  trust-remote-code: true
  block-size: 64
  max-model-len: 32768
  max-num-batched-tokens: 32768
  tensor-parallel-size: 1
  enforce-eager: false
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
